### ISSUE TITLE
python3 only

### ISSUE THREAD

**Issue by Deepwalker** [PythonRails/rails#2]
If you create new thing – its meaningful to work with python2 branch. Train already is far away – asyncio, yield from, you name it. Its just does not make sense to create new thing for old branch, that almost unsupported – security bugfixes is not real support.

**Comment by 1st** [comment]
You are correct! We use python-compatible code here. When we will find that we need switch to Python 3 because we can't use some old tools - we do this. Current code can be run on python3 without errors. But to be sure - we need to create some tests for this.
